# Generated by Django 2.1.3 on 2018-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlzippr', '0006_auto_20181108_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='encrypted_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
